[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "owasp-dependency-track-client"
dynamic = ["version"]
description = "Inofficial OWASP Dependency Track API Python client"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attrs>=26.1.0",
    "httpx>=0.28.1",
    "python-dateutil>=2.9.0.post0",
]

[project.optional-dependencies]
build = [
    "build",
    "twine",
]

test = [
    "pytest==9.1.1",
    "pytest-depends==1.0.1",
    "pytest-cov==7.1.0",
    "dotenv==0.9.9",
    "openapi-python-client==0.29.1",
    "tinystream==0.1.18",
    "is_empty==1.0.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["owasp_dt*", "owasp_dt_v2*"]
exclude = ["test*", "tmp*"]
