from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.cel_expression_error import CelExpressionError


T = TypeVar("T", bound="InvalidNotificationFilterExpressionProblemDetails")


@_attrs_define
class InvalidNotificationFilterExpressionProblemDetails:
    """
    Attributes:
        detail (str): Human-readable explanation specific to this occurrence of the problem Example: Example detail.
        status (int): HTTP status code generated by the origin server for this occurrence of the problem Example: 400.
        title (str): Short, human-readable summary of the problem type Example: Example title.
        instance (str | Unset): Reference URI that identifies the specific occurrence of the problem Example:
            https://api.example.org/foo/bar/example-instance.
        type_ (str | Unset): A URI reference that identifies the problem type Example:
            https://api.example.org/foo/bar/example-problem.
        errors (list[CelExpressionError] | Unset): Errors identified during CEL expression compilation
    """

    detail: str
    status: int
    title: str
    instance: str | Unset = UNSET
    type_: str | Unset = UNSET
    errors: list[CelExpressionError] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        detail = self.detail

        status = self.status

        title = self.title

        instance = self.instance

        type_ = self.type_

        errors: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.errors, Unset):
            errors = []
            for errors_item_data in self.errors:
                errors_item = errors_item_data.to_dict()
                errors.append(errors_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "detail": detail,
                "status": status,
                "title": title,
            }
        )
        if instance is not UNSET:
            field_dict["instance"] = instance
        if type_ is not UNSET:
            field_dict["type"] = type_
        if errors is not UNSET:
            field_dict["errors"] = errors

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        from ..models.cel_expression_error import CelExpressionError

        d = dict(src_dict)
        detail = d.pop("detail")

        status = d.pop("status")

        title = d.pop("title")

        instance = d.pop("instance", UNSET)

        type_ = d.pop("type", UNSET)

        _errors = d.pop("errors", UNSET)
        errors: list[CelExpressionError] | Unset = UNSET
        if _errors is not UNSET:
            errors = []
            for errors_item_data in _errors:
                errors_item = CelExpressionError.from_dict(errors_item_data)

                errors.append(errors_item)

        invalid_notification_filter_expression_problem_details = cls(
            detail=detail,
            status=status,
            title=title,
            instance=instance,
            type_=type_,
            errors=errors,
        )

        invalid_notification_filter_expression_problem_details.additional_properties = d
        return invalid_notification_filter_expression_problem_details

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
