from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="TeamAlreadyExistsProblemDetails")


@_attrs_define
class TeamAlreadyExistsProblemDetails:
    """
    Attributes:
        detail (str): Human-readable explanation specific to this occurrence of the problem Example: Example detail.
        status (int): HTTP status code generated by the origin server for this occurrence of the problem Example: 400.
        title (str): Short, human-readable summary of the problem type Example: Example title.
        instance (str | Unset): Reference URI that identifies the specific occurrence of the problem Example:
            https://api.example.org/foo/bar/example-instance.
        team_name (str | Unset): Name of the existing team
        team_uuid (UUID | Unset): UUID of the existing team
        type_ (str | Unset): A URI reference that identifies the problem type Example:
            https://api.example.org/foo/bar/example-problem.
    """

    detail: str
    status: int
    title: str
    instance: str | Unset = UNSET
    team_name: str | Unset = UNSET
    team_uuid: UUID | Unset = UNSET
    type_: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        detail = self.detail

        status = self.status

        title = self.title

        instance = self.instance

        team_name = self.team_name

        team_uuid: str | Unset = UNSET
        if not isinstance(self.team_uuid, Unset):
            team_uuid = str(self.team_uuid)

        type_ = self.type_

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "detail": detail,
                "status": status,
                "title": title,
            }
        )
        if instance is not UNSET:
            field_dict["instance"] = instance
        if team_name is not UNSET:
            field_dict["teamName"] = team_name
        if team_uuid is not UNSET:
            field_dict["teamUuid"] = team_uuid
        if type_ is not UNSET:
            field_dict["type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        detail = d.pop("detail")

        status = d.pop("status")

        title = d.pop("title")

        instance = d.pop("instance", UNSET)

        team_name = d.pop("teamName", UNSET)

        _team_uuid = d.pop("teamUuid", UNSET)
        team_uuid: UUID | Unset
        if isinstance(_team_uuid, Unset):
            team_uuid = UNSET
        else:
            team_uuid = UUID(_team_uuid)

        type_ = d.pop("type", UNSET)

        team_already_exists_problem_details = cls(
            detail=detail,
            status=status,
            title=title,
            instance=instance,
            team_name=team_name,
            team_uuid=team_uuid,
            type_=type_,
        )

        team_already_exists_problem_details.additional_properties = d
        return team_already_exists_problem_details

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
